import { Platform, StatusBar, StyleSheet } from "react-native";

const brand = {
  primary: "#256F63",
  cream: "#F7F2E8",
  paper: "#FFFDF8",
  border: "#D8CCBC",
  ink: "#21302C",
  muted: "#766E64",
  soft: "#E5F1ED",
};

const androidTopInset = Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) + 6 : 0;
const navBottomInset = Platform.OS === "android" ? 52 : 28;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: brand.cream, paddingTop: androidTopInset },
  safeAreaDark: { backgroundColor: "#0f172a" },
  app: { flex: 1 },
  appDark: { backgroundColor: "#0f172a" },
  content: { padding: 14, paddingBottom: navBottomInset + 150 },
  onboardingContent: { flexGrow: 1, justifyContent: "center", padding: 18 },
  onboardingPanel: { borderRadius: 8, backgroundColor: "#fff", borderWidth: 1, borderColor: brand.border, padding: 18, gap: 12 },
  onboardingTitle: { color: brand.ink, fontSize: 30, lineHeight: 34, fontWeight: "900" },
  onboardingList: { gap: 8, marginBottom: 8 },
  onboardingMember: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 10 },
  onboardingProgressRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  onboardingStepPill: { flexGrow: 1, flexBasis: 92, minHeight: 52, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", paddingHorizontal: 10, paddingVertical: 8, justifyContent: "center" },
  setupChoiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  setupChoiceCard: { flexGrow: 1, flexBasis: 144, minHeight: 92, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, justifyContent: "center" },
  profileGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  profileCard: { flexGrow: 1, flexBasis: 132, minHeight: 84, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 10, justifyContent: "center" },
  startPlanPreview: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 8 },
  header: { gap: 10, paddingHorizontal: 14, paddingTop: 12, paddingBottom: 14 },
  headerDark: { backgroundColor: "#0f172a" },
  headerTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  headerControls: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  brandMark: { width: 44, height: 44, borderRadius: 8, backgroundColor: brand.primary, alignItems: "center", justifyContent: "center" },
  brandMarkImage: { width: 44, height: 44, borderRadius: 8 },
  brandMarkText: { color: "#fff", fontWeight: "900" },
  headerTitle: { flex: 1 },
  eyebrow: { color: brand.muted, fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  title: { color: brand.ink, fontSize: 22, fontWeight: "900" },
  textDark: { color: "#f8fafc" },
  mutedDark: { color: "#cbd5e1" },
  weekStepper: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 1 },
  stepButton: { width: 44, height: 44, borderRadius: 8, backgroundColor: brand.paper, borderWidth: 1, borderColor: brand.border, alignItems: "center", justifyContent: "center" },
  stepButtonText: { color: brand.primary, fontSize: 22, fontWeight: "900" },
  weekChip: { borderRadius: 999, backgroundColor: brand.paper, borderWidth: 1, borderColor: brand.border, paddingHorizontal: 12, paddingVertical: 9 },
  weekChipText: { color: "#6a6259", fontWeight: "900" },
  todayButton: { borderRadius: 8, backgroundColor: brand.primary, paddingHorizontal: 12, paddingVertical: 10 },
  todayButtonText: { color: "#fff", fontWeight: "900" },
  modeButton: { borderRadius: 8, backgroundColor: "#fffaf2", borderWidth: 1, borderColor: "#ded6ca", paddingHorizontal: 10, paddingVertical: 10 },
  modeButtonDark: { backgroundColor: "#1e293b", borderColor: "#334155" },
  modeButtonText: { color: "#6a6259", fontWeight: "900", fontSize: 12 },
  modeButtonTextDark: { color: "#f8fafc" },
  panel: { borderRadius: 8, backgroundColor: "#fff", borderWidth: 1, borderColor: "#ded6ca", padding: 16, gap: 10 },
  panelDark: { backgroundColor: "#111827", borderColor: "#334155" },
  heroTitle: { color: "#202124", fontSize: 26, lineHeight: 30, fontWeight: "900" },
  heroText: { color: "#6a6259", lineHeight: 22 },
  syncPill: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  syncDot: { width: 8, height: 8, borderRadius: 4 },
  syncText: { fontSize: 12, fontWeight: "900" },
  statusNotice: { alignSelf: "stretch", borderRadius: 8, borderWidth: 1, padding: 10, gap: 4 },
  rowScroll: { marginHorizontal: -2 },
  dayButton: { minWidth: 76, borderRadius: 8, backgroundColor: "#fffaf2", borderWidth: 1, borderColor: "#ded6ca", padding: 9, marginRight: 8 },
  dayButtonActive: { backgroundColor: brand.primary, borderColor: brand.primary },
  dayButtonText: { color: "#6a6259", fontWeight: "900" },
  dayButtonTextActive: { color: "#fff" },
  dayDate: { color: "#202124", fontWeight: "900", marginTop: 2 },
  memberButton: { flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 8, backgroundColor: "#fffaf2", borderWidth: 1, borderColor: "#ded6ca", paddingHorizontal: 12, paddingVertical: 10, marginRight: 8 },
  memberButtonActive: { backgroundColor: brand.primary, borderColor: brand.primary },
  memberButtonText: { color: "#6a6259", fontWeight: "900" },
  memberButtonTextActive: { color: "#fff" },
  dot: { width: 10, height: 10, borderRadius: 5 },
  progressBox: { backgroundColor: brand.soft, borderRadius: 8, padding: 16, alignItems: "center" },
  progressBoxDark: { backgroundColor: "#1e293b" },
  progressNumber: { color: "#202124", fontSize: 28, fontWeight: "900" },
  muted: { color: "#6a6259", fontWeight: "700" },
  permissionHint: { color: "#6a6259", fontWeight: "800", lineHeight: 20, marginBottom: 12 },
  disabledButton: { opacity: 0.45 },
  disabledText: { color: "#e5e7eb" },
  section: { marginTop: 14, borderRadius: 8, backgroundColor: "#fff", borderWidth: 1, borderColor: "#ded6ca", padding: 16 },
  sectionDark: { backgroundColor: "#111827", borderColor: "#334155" },
  sectionTitle: { color: "#202124", fontSize: 20, fontWeight: "900", marginBottom: 12 },
  taskRow: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  rowDark: { backgroundColor: "#1e293b", borderColor: "#334155" },
  taskRowDone: { backgroundColor: "#edf5f2" },
  checkBox: { width: 44, height: 44, borderRadius: 8, borderWidth: 2, borderColor: "#ded6ca", alignItems: "center", justifyContent: "center" },
  checkText: { color: brand.primary, fontWeight: "900" },
  taskTextBox: { flex: 1, minWidth: 0 },
  taskTitle: { color: "#202124", fontWeight: "900" },
  taskMeta: { color: "#6a6259", fontSize: 12, marginTop: 4 },
  todayFocusBand: { borderRadius: 8, padding: 12, marginBottom: 12 },
  thanksMoment: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 12 },
  todayActionRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  todayGroup: { marginTop: 4, marginBottom: 4 },
  todayListHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginTop: 6, marginBottom: 8 },
  emptyStateCard: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: brand.soft, padding: 12, marginBottom: 10, gap: 10 },
  unit: { minWidth: 42, textAlign: "center", borderRadius: 999, backgroundColor: "#f1eee8", padding: 8, fontWeight: "900" },
  mealBox: { marginTop: 8, backgroundColor: "#fffaf2", borderRadius: 8, padding: 12 },
  mealBoxDark: { backgroundColor: "#1e293b" },
  mealTitle: { color: "#202124", fontSize: 18, fontWeight: "900", marginTop: 4 },
  summaryGrid: { flexDirection: "row", gap: 8, marginBottom: 14 },
  summaryTile: { flex: 1, minHeight: 78, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 10, justifyContent: "center" },
  summaryNumber: { color: "#202124", fontSize: 22, fontWeight: "900" },
  summaryLabel: { color: "#6a6259", fontSize: 12, fontWeight: "800", marginTop: 3 },
  daySection: { marginBottom: 14 },
  dayHeading: { color: "#202124", fontWeight: "900", marginBottom: 6 },
  weekLine: { color: "#6a6259", marginBottom: 4 },
  weekPreviewRow: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 8 },
  weekPreviewRowActive: { borderColor: brand.primary },
  weekPreviewMeta: { flex: 1 },
  weekPreviewTitle: { color: "#202124", fontWeight: "900" },
  weekPreviewStats: { alignItems: "flex-end" },
  weekTaskRow: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 8 },
  scoreRow: { flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: "#f1eee8", paddingVertical: 11 },
  scoreCard: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 8 },
  scoreHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
  scoreName: { flex: 1, color: "#202124", fontWeight: "900" },
  scoreDelta: { width: 58, textAlign: "right", fontWeight: "900" },
  scoreHigh: { color: "#c2410c" },
  scoreLow: { color: "#2563eb" },
  scoreEven: { color: brand.primary },
  fairnessInsightBand: { borderRadius: 8, padding: 12, marginBottom: 12 },
  fairnessStatusPill: { borderRadius: 999, borderWidth: 1, borderColor: "#ded6ca", paddingHorizontal: 8, paddingVertical: 4, fontSize: 11, fontWeight: "900", overflow: "hidden" },
  scoreAdvice: { color: "#6a6259", fontSize: 12, fontWeight: "800", lineHeight: 18, marginTop: 8 },
  scoreDetailGrid: { flexDirection: "row", gap: 8, marginTop: 10 },
  scoreDetail: { flex: 1, color: "#6a6259", fontSize: 12, fontWeight: "800" },
  scoreDetailStrong: { flex: 1, color: "#202124", fontSize: 12, fontWeight: "900" },
  scoreUnits: { color: "#202124", fontWeight: "900" },
  fairnessBarGroup: { gap: 7, marginTop: 12 },
  fairnessBarRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  fairnessBarLabel: { width: 34, color: "#6a6259", fontSize: 12, fontWeight: "900" },
  fairnessBarTrack: { flex: 1, height: 10, borderRadius: 999, backgroundColor: "#f1eee8", overflow: "hidden" },
  fairnessBarFill: { height: 10, borderRadius: 999 },
  fairnessBarValue: { width: 42, textAlign: "right", color: "#202124", fontSize: 12, fontWeight: "900" },
  weekTrendRow: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 10, marginBottom: 8 },
  weekTrendTrack: { flex: 1, height: 12, borderRadius: 999, backgroundColor: "#f1eee8", overflow: "hidden" },
  weekTrendFill: { height: 12, borderRadius: 999 },
  assignmentEditor: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  defaultAssignBox: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 10 },
  fairAssignBox: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  fairAssignPreview: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8, marginBottom: 10 },
  fairAssignChip: { flexGrow: 1, flexBasis: 92, minHeight: 52, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 8, justifyContent: "center" },
  smallMemberButton: { width: 44, height: 44, borderRadius: 8, backgroundColor: "#fffaf2", borderWidth: 1, borderColor: "#ded6ca", alignItems: "center", justifyContent: "center", marginRight: 8, marginTop: 8 },
  smallMemberButtonActive: { backgroundColor: brand.primary, borderColor: brand.primary },
  smallMemberButtonText: { color: "#6a6259", fontWeight: "900" },
  smallMemberButtonTextActive: { color: "#fff" },
  mealRow: { alignItems: "stretch", gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#f1eee8" },
  mealRowSelected: { backgroundColor: brand.soft, borderRadius: 8, paddingHorizontal: 8 },
  mealHeaderRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  mealInfoRow: { flexDirection: "row", alignItems: "center", gap: 10, width: "100%" },
  mealDay: { width: 78, color: "#6a6259", fontWeight: "900" },
  mealName: { flex: 1, color: "#202124", fontWeight: "800" },
  mealActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: 8, width: "100%" },
  input: { minHeight: 44, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", paddingHorizontal: 12, marginBottom: 10, backgroundColor: "#fffaf2" },
  inputDark: { backgroundColor: "#0f172a", borderColor: "#334155", color: "#f8fafc" },
  primaryAction: { minHeight: 44, borderRadius: 8, backgroundColor: brand.primary, alignItems: "center", justifyContent: "center", marginBottom: 16 },
  primaryActionInline: { flexGrow: 1, flexShrink: 1, minWidth: 132, minHeight: 44, borderRadius: 8, backgroundColor: brand.primary, alignItems: "center", justifyContent: "center" },
  primaryActionText: { color: "#fff", fontWeight: "900" },
  secondaryAction: { flexGrow: 1, flexShrink: 1, minWidth: 132, minHeight: 44, borderRadius: 8, backgroundColor: "#f1eee8", alignItems: "center", justifyContent: "center" },
  secondaryActionFull: { minHeight: 44, borderRadius: 8, backgroundColor: "#f1eee8", alignItems: "center", justifyContent: "center", marginBottom: 12 },
  secondaryActionText: { color: "#6a6259", fontWeight: "900" },
  actionInline: { flex: 1, marginTop: 0 },
  editorActions: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  editorRow: { flexDirection: "column", alignItems: "stretch", alignSelf: "stretch" },
  editButton: { minHeight: 44, minWidth: 96, borderRadius: 8, borderWidth: 1, borderColor: brand.primary, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" },
  editButtonText: { color: brand.primary, fontWeight: "900", fontSize: 12 },
  deleteButton: { minHeight: 44, minWidth: 88, borderRadius: 8, borderWidth: 1, borderColor: "#b91c1c", paddingHorizontal: 10, alignItems: "center", justifyContent: "center" },
  deleteButtonWide: { minHeight: 44, borderRadius: 8, borderWidth: 1, borderColor: "#b91c1c", alignItems: "center", justifyContent: "center", marginTop: 4 },
  deleteButtonText: { color: "#b91c1c", fontWeight: "900", fontSize: 12 },
  segmented: { flexDirection: "row", gap: 8, marginBottom: 10 },
  segmentedWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  segmentButton: { flex: 1, minHeight: 44, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", alignItems: "center", justifyContent: "center", backgroundColor: "#fffaf2" },
  segmentButtonCompact: { minHeight: 44, minWidth: 92, flexGrow: 1, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", alignItems: "center", justifyContent: "center", backgroundColor: "#fffaf2", paddingHorizontal: 10 },
  segmentButtonActive: { backgroundColor: brand.primary, borderColor: brand.primary },
  segmentButtonText: { color: "#6a6259", fontWeight: "900" },
  segmentButtonTextActive: { color: "#fff" },
  packageGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  packageLibrary: { marginBottom: 12 },
  packageCard: { width: "48%", minWidth: 138, flexGrow: 1, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 10 },
  packageTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 6 },
  dayToggleGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  dayToggle: { width: 44, height: 44, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", alignItems: "center", justifyContent: "center" },
  dayToggleActive: { backgroundColor: brand.primary, borderColor: brand.primary },
  dayToggleText: { color: "#6a6259", fontWeight: "900" },
  dayToggleTextActive: { color: "#fff" },
  swatches: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  swatch: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: "transparent" },
  swatchActive: { borderColor: "#202124" },
  memberEditorRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  memberSummary: { flexDirection: "row", alignItems: "center", gap: 12, width: "100%" },
  memberActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: 10, width: "100%" },
  memberAvatar: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" },
  memberAvatarText: { color: "#fff", fontWeight: "900" },
  privacyBox: { borderRadius: 8, borderWidth: 1, borderColor: brand.border, backgroundColor: brand.paper, padding: 12, marginTop: 8 },
  privacyText: { color: brand.muted, fontWeight: "700", lineHeight: 20, marginBottom: 8 },
  settingsCard: { borderRadius: 8, borderWidth: 1, borderColor: brand.border, backgroundColor: brand.paper, padding: 12, marginBottom: 10 },
  accountStatusRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  compactInfoBox: { borderRadius: 8, borderWidth: 1, borderColor: brand.border, padding: 10, marginBottom: 12 },
  preferenceRow: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 8 },
  preferenceText: { flex: 1, minWidth: 0 },
  toggleButton: { minWidth: 76, minHeight: 38, borderRadius: 999, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#f1eee8", alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  toggleButtonActive: { backgroundColor: brand.primary, borderColor: brand.primary },
  toggleButtonText: { color: "#6a6259", fontSize: 12, fontWeight: "900" },
  toggleButtonTextActive: { color: "#fff" },
  quietTimeRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 8 },
  quietTimeField: { flexGrow: 1, flexBasis: 104, minWidth: 104 },
  designSetRow: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 10 },
  designSetRowActive: { borderColor: brand.primary, borderWidth: 2 },
  designSwatch: { width: 44, height: 44, borderRadius: 22 },
  readinessBadge: { color: "#6a6259", fontSize: 12, fontWeight: "900" },
  remoteRow: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginTop: 10 },
  memberPreviewGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  memberPreviewChip: { flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 999, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", paddingHorizontal: 10, paddingVertical: 6 },
  spacedTitle: { marginTop: 8 },
  templateRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  taskEditorCard: { alignSelf: "stretch", borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  templateSummary: { flexDirection: "row", alignItems: "center", gap: 10, width: "100%" },
  templateActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: 10, width: "100%" },
  mealEditorRow: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", padding: 12, marginBottom: 10 },
  mealInput: { marginTop: 8 },
  longtermMealWeek: { borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 12, marginBottom: 10 },
  longtermMealGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  longtermMealCell: { width: "30%", minWidth: 86, borderRadius: 8, backgroundColor: "#fff", borderWidth: 1, borderColor: "#f1eee8", padding: 8 },
  longtermMealTitle: { color: "#202124", fontWeight: "800", fontSize: 12, marginTop: 2 },
  longtermTaskRow: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 8, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 10, marginBottom: 8 },
  nav: { position: "absolute", left: 10, right: 10, bottom: navBottomInset, flexDirection: "row", gap: 4, borderRadius: 12, borderWidth: 1, borderColor: "#ded6ca", backgroundColor: "#fffaf2", padding: 6 },
  navDark: { backgroundColor: "#1e293b", borderColor: "#334155" },
  navButton: { flex: 1, minHeight: 50, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  navButtonActive: { backgroundColor: brand.primary },
  navText: { color: "#6a6259", fontSize: 12, fontWeight: "900" },
  navTextActive: { color: "#fff" },
});
